# Generated by Django 4.1 on 2022-08-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haehoouser',
            name='nickname',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
